### ISSUE TITLE
TimeoutError: Knex: Timeout acquiring a connection.

### ISSUE THREAD

**Issue by csehlke** [Rostlab/JS18_ProjectA_Group2#82]
Maybe an error; it occured while the app was still run when I checkout a different version and it had to recompne. (both versions are the same as the current #77 in the backend part)
Maybe someone has an idea where this might come from

Server listening at 127.0.0.1:3001
[1] 2018-04-08T17:55:10.509Z - info: getTable started...
[1] { TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
[1]     at C:\Users\Carsten\Documents\Uni\JS18_ProjectA_Group2\node_modules\knex\lib\client.js:326:13
[1]     at tryCatcher (C:\Users\Carsten\Documents\Uni\JS18_ProjectA_Group2\node_modules\bluebird\js\release\util.js:16:23)
[1]     at C:\Users\Carsten\Documents\Uni\JS18_ProjectA_Group2\node_modules\bluebird\js\release\catch_filter.js:17:41
[1]     at tryCatcher (C:\Users\Carsten\Documents\Uni\JS18_ProjectA_Group2\node_modules\bluebird\js\release\util.js:16:23)
[1]     at Promise._settlePromiseFromHandler (C:\Users\Carsten\Documents\Uni\JS18_ProjectA_Group2\node_modules\bluebird\js\release\promise.js:512:31)
[1]     at Promise._settlePromise (C:\Users\Carsten\Documents\Uni\JS18_ProjectA_Group2\node_modules\bluebird\js\release\promise.js:569:18)
[1]     at Promise._settlePromise0 (C:\Users\Carsten\Documents\Uni\JS18_ProjectA_Group2\node_modules\bluebird\js\release\promise.js:614:10)
[1]     at Promise._settlePromises (C:\Users\Carsten\Documents\Uni\JS18_ProjectA_Group2\node_modules\bluebird\js\release\promise.js:689:18)
[1]     at Async._drainQueue (C:\Users\Carsten\Documents\Uni\JS18_ProjectA_Group2\node_modules\bluebird\js\release\async.js:133:16)
[1]     at Async._drainQueues (C:\Users\Carsten\Documents\Uni\JS18_ProjectA_Group2\node_modules\bluebird\js\release\async.js:143:10)
[1]     at Immediate.Async.drainQueues (C:\Users\Carsten\Documents\Uni\JS18_ProjectA_Group2\node_modules\bluebird\js\release\async.js:17:14)
[1]     at runCallback (timers.js:672:20)
[1]     at tryOnImmediate (timers.js:645:5)
[1]     at processImmediate [as _immediateCallback] (timers.js:617:5) sql: undefined, bindings: undefined }
[1] Err

**Comment by csehlke** [comment]
seems to be a promlem that only appears when the branch is not checked out completly
